[template]
cargo_generate_version = ">=0.9.0"

[hooks]
pre = ["ask-license.rhai"]

[placeholders]
project-description = { type = "string", prompt = "😄please provide some description to the project?", default = "A axum base rust web project" }